-- CreateTable
CREATE TABLE "insurance_claims" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "claimNumber" TEXT NOT NULL,
    "admissionId" TEXT NOT NULL,
    "billingId" TEXT NOT NULL,
    "policyNumber" TEXT NOT NULL,
    "insuranceProvider" TEXT NOT NULL,
    "tpaName" TEXT,
    "claimType" TEXT NOT NULL,
    "claimedAmount" REAL NOT NULL,
    "approvedAmount" REAL NOT NULL DEFAULT 0,
    "rejectedAmount" REAL NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "diagnosisCode" TEXT,
    "treatmentCode" TEXT,
    "preAuthNumber" TEXT,
    "preAuthDate" DATETIME,
    "preAuthAmount" REAL,
    "preAuthStatus" TEXT,
    "reviewedDate" DATETIME,
    "reviewedBy" TEXT,
    "rejectionReason" TEXT,
    "reviewRemarks" TEXT,
    "tpaReferenceNumber" TEXT,
    "settlementNumber" TEXT,
    "settlementDate" DATETIME,
    "settlementAmount" REAL,
    "remarks" TEXT,
    "attachments" TEXT,
    "isEmergency" BOOLEAN NOT NULL DEFAULT false,
    "contactPerson" TEXT,
    "contactPhone" TEXT,
    "urgency" TEXT,
    "validityPeriod" TEXT,
    "conditions" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "insurance_claims_admissionId_fkey" FOREIGN KEY ("admissionId") REFERENCES "admissions" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT "insurance_claims_billingId_fkey" FOREIGN KEY ("billingId") REFERENCES "ipd_billing" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE UNIQUE INDEX "insurance_claims_claimNumber_key" ON "insurance_claims"("claimNumber");
