-- CreateTable
CREATE TABLE "opd_visits" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "visitId" TEXT NOT NULL,
    "patientId" TEXT NOT NULL,
    "visitDate" DATETIME NOT NULL,
    "department" TEXT NOT NULL,
    "consultingDoctorId" TEXT,
    "doctorSpecialization" TEXT,
    "visitType" TEXT NOT NULL DEFAULT 'OPD',
    "referralSource" TEXT,
    "appointmentMode" TEXT NOT NULL DEFAULT 'Walk_in',
    "tokenNumber" TEXT,
    "appointmentSlot" TEXT,
    "visitPriority" TEXT NOT NULL DEFAULT 'Normal',
    "visitStatus" TEXT NOT NULL DEFAULT 'Pending',
    "followUpSuggestedDays" INTEGER,
    "heightCm" REAL,
    "weightKg" REAL,
    "bmi" REAL,
    "temperature" REAL,
    "bloodPressure" TEXT,
    "pulseRate" INTEGER,
    "respiratoryRate" INTEGER,
    "spo2" INTEGER,
    "weightNote" TEXT,
    "chiefComplaint" TEXT NOT NULL,
    "durationOfSymptoms" TEXT,
    "historyOfPresentIllness" TEXT NOT NULL,
    "pastMedicalHistory" TEXT,
    "familyHistory" TEXT,
    "personalHistory" TEXT,
    "generalExamination" TEXT,
    "systemicExamination" TEXT,
    "allergiesDetailed" TEXT,
    "provisionalDiagnosis" TEXT,
    "finalDiagnosis" TEXT,
    "icd10Codes" TEXT,
    "prescriptionList" TEXT,
    "proceduresDone" TEXT,
    "treatmentNotes" TEXT,
    "recommendedLabTests" TEXT,
    "radiologyTests" TEXT,
    "investigationUrgency" TEXT,
    "consultationFee" REAL NOT NULL,
    "investigationEstimate" REAL,
    "procedureCharges" REAL,
    "discountAmount" REAL,
    "totalPayable" REAL NOT NULL,
    "paymentMode" TEXT,
    "paymentStatus" TEXT NOT NULL DEFAULT 'PENDING',
    "insuranceCompany" TEXT,
    "insurancePolicyNumber" TEXT,
    "insurancePreAuthRequired" BOOLEAN,
    "followUpDate" DATETIME,
    "followUpInstructions" TEXT,
    "referToIPD" BOOLEAN NOT NULL DEFAULT false,
    "referralNote" TEXT,
    "createdBy" TEXT,
    "modifiedBy" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "opd_visits_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "patients" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "opd_visits_consultingDoctorId_fkey" FOREIGN KEY ("consultingDoctorId") REFERENCES "doctors" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);

-- RedefineTables
PRAGMA defer_foreign_keys=ON;
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_patients" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "patientId" TEXT NOT NULL,
    "firstName" TEXT NOT NULL,
    "lastName" TEXT,
    "email" TEXT,
    "phone" TEXT NOT NULL,
    "dateOfBirth" DATETIME NOT NULL,
    "gender" TEXT NOT NULL,
    "address" TEXT,
    "city" TEXT NOT NULL DEFAULT '',
    "state" TEXT NOT NULL DEFAULT '',
    "zipCode" TEXT NOT NULL DEFAULT '',
    "emergencyContactName" TEXT NOT NULL DEFAULT '',
    "emergencyContactPhone" TEXT NOT NULL DEFAULT '',
    "emergencyContactRelationship" TEXT NOT NULL DEFAULT '',
    "bloodGroup" TEXT,
    "allergies" TEXT,
    "chronicConditions" TEXT,
    "currentMedications" TEXT,
    "insuranceProvider" TEXT,
    "insurancePolicyNumber" TEXT,
    "guardianName" TEXT,
    "guardianRelation" TEXT,
    "occupation" TEXT,
    "idProofType" TEXT,
    "idProofNumber" TEXT,
    "patientType" TEXT NOT NULL DEFAULT 'NEW',
    "medicalHistory" TEXT,
    "familyHistory" TEXT,
    "personalHistory" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "avatar" TEXT,
    "notes" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "userId" TEXT,
    CONSTRAINT "patients_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE CASCADE
);
INSERT INTO "new_patients" ("address", "allergies", "avatar", "bloodGroup", "chronicConditions", "city", "createdAt", "currentMedications", "dateOfBirth", "email", "emergencyContactName", "emergencyContactPhone", "emergencyContactRelationship", "firstName", "gender", "id", "insurancePolicyNumber", "insuranceProvider", "isActive", "lastName", "notes", "patientId", "phone", "state", "updatedAt", "userId", "zipCode") SELECT "address", "allergies", "avatar", "bloodGroup", "chronicConditions", "city", "createdAt", "currentMedications", "dateOfBirth", "email", "emergencyContactName", "emergencyContactPhone", "emergencyContactRelationship", "firstName", "gender", "id", "insurancePolicyNumber", "insuranceProvider", "isActive", "lastName", "notes", "patientId", "phone", "state", "updatedAt", "userId", "zipCode" FROM "patients";
DROP TABLE "patients";
ALTER TABLE "new_patients" RENAME TO "patients";
CREATE UNIQUE INDEX "patients_patientId_key" ON "patients"("patientId");
CREATE UNIQUE INDEX "patients_userId_key" ON "patients"("userId");
PRAGMA foreign_keys=ON;
PRAGMA defer_foreign_keys=OFF;

-- CreateIndex
CREATE UNIQUE INDEX "opd_visits_visitId_key" ON "opd_visits"("visitId");
